name: Create Pull Request for serwery.txt

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
  schedule:
    - cron: "0 0 * * 0"  # Raz w tygodniu w niedzielę o północy

jobs:
  update-serwery:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download serwery.txt
      run: |
        wget -O serwery.txt https://mikr.us/serwery.txt
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add serwery.txt
        git commit -m "Update serwery.txt"
        git push

    - name: Create Pull Request
      run: |
        hub pull-request -m "Update serwery.txt"
