name: Create Pull Request for serwery.txt

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
  schedule:
    - cron: "0 0 * * 0"

jobs:
  update-serwery:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create or use a feature branch
      run: |
        git checkout -b feature/update-serwery-txt
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git pull origin main

    - name: Download serwery.txt
      run: |
        wget -O serwery.txt https://mikr.us/serwery.txt

    - name: Create Pull Request
      run: |
        git add serwery.txt
        git commit -m "Update serwery.txt"
        git push origin feature/update-serwery-txt
        gh pr create --base main --head feature/update-serwery-txt --title "Update serwery.txt" --body "Update serwery.txt"
