name: Update serwery.txt

on:
  push:
    branches:
      - main  # Zmieniaj na główną gałąź, jeśli to inna gałąź

jobs:
  update-serwery:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download serwery.txt
      run: |
        wget -O serwery.txt https://mikr.us/serwery.txt
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add serwery.txt
        git commit -m "Update serwery.txt"
        git push
